@STHEnterprise.Api_HostAddress = http://localhost:5170

GET {{STHEnterprise.Api_HostAddress}}/weatherforecast/
Accept: application/json

###


GET {{STHEnterprise.Api_HostAddress}}/api/v1.0/account/admin-only/
Accept: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjZiMWNmNWNiLTIzYTAtNGEwZS1hMGU4LWVmYjNhNDY2MDBjZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQHN0aC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiU3lzdGVtIEFkbWluIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3Njc3MDgzMzIsImlzcyI6IlNUSEVudGVycHJpc2UiLCJhdWQiOiJTVEhFbnRlcnByaXNlVXNlcnMifQ.BxLMjAkufoiK1jU_p6zkDKs8dBxEEF7dxSUfZc47LH8"


}