// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WalletSystem.Data;

#nullable disable

namespace WalletSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260327090053_FixDecimalColumnTypes")]
    partial class FixDecimalColumnTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("WalletSystem.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("REAL");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BalanceBefore")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RelatedWalletId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WalletId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.HasIndex("RelatedWalletId");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2000m,
                            BalanceAfter = 2000m,
                            BalanceBefore = 0m,
                            CreatedAt = new DateTime(2024, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Initial deposit",
                            ReferenceNumber = "REF-001",
                            Status = "Completed",
                            Type = "Deposit",
                            WalletId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 500m,
                            BalanceAfter = 1500m,
                            BalanceBefore = 2000m,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ATM withdrawal",
                            ReferenceNumber = "REF-002",
                            Status = "Completed",
                            Type = "Withdrawal",
                            WalletId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 500m,
                            BalanceAfter = 500m,
                            BalanceBefore = 0m,
                            CreatedAt = new DateTime(2024, 1, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bank transfer in",
                            ReferenceNumber = "REF-003",
                            Status = "Completed",
                            Type = "Deposit",
                            WalletId = 2
                        },
                        new
                        {
                            Id = 4,
                            Amount = 179.50m,
                            BalanceAfter = 320.50m,
                            BalanceBefore = 500m,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Online purchase",
                            ReferenceNumber = "REF-004",
                            Status = "Completed",
                            Type = "Withdrawal",
                            WalletId = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 10000m,
                            BalanceAfter = 10000m,
                            BalanceBefore = 0m,
                            CreatedAt = new DateTime(2024, 1, 4, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wire transfer",
                            ReferenceNumber = "REF-005",
                            Status = "Completed",
                            Type = "Deposit",
                            WalletId = 4
                        },
                        new
                        {
                            Id = 6,
                            Amount = 199.25m,
                            BalanceAfter = 9800.75m,
                            BalanceBefore = 10000m,
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Monthly fee",
                            ReferenceNumber = "REF-006",
                            Status = "Completed",
                            Type = "Fee",
                            WalletId = 4
                        },
                        new
                        {
                            Id = 7,
                            Amount = 100m,
                            BalanceAfter = 1400m,
                            BalanceBefore = 1500m,
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Transfer to Bob",
                            ReferenceNumber = "REF-007",
                            RelatedWalletId = 2,
                            Status = "Completed",
                            Type = "Transfer",
                            WalletId = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = 100m,
                            BalanceAfter = 420.50m,
                            BalanceBefore = 320.50m,
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Transfer from Alice",
                            ReferenceNumber = "REF-008",
                            RelatedWalletId = 1,
                            Status = "Completed",
                            Type = "Transfer",
                            WalletId = 2
                        },
                        new
                        {
                            Id = 9,
                            Amount = 50m,
                            BalanceAfter = 1450m,
                            BalanceBefore = 1400m,
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Referral bonus",
                            ReferenceNumber = "REF-009",
                            Status = "Completed",
                            Type = "Bonus",
                            WalletId = 1
                        },
                        new
                        {
                            Id = 10,
                            Amount = 50m,
                            BalanceAfter = 1500m,
                            BalanceBefore = 1450m,
                            CreatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Refund from merchant",
                            ReferenceNumber = "REF-010",
                            Status = "Completed",
                            Type = "Refund",
                            WalletId = 1
                        });
                });

            modelBuilder.Entity("WalletSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice@example.com",
                            FullName = "Alice Johnson",
                            PhoneNumber = "555-0101",
                            Status = "Active",
                            Username = "alice"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob@example.com",
                            FullName = "Bob Martinez",
                            PhoneNumber = "555-0102",
                            Status = "Active",
                            Username = "bob"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carol@example.com",
                            FullName = "Carol White",
                            PhoneNumber = "555-0103",
                            Status = "Inactive",
                            Username = "carol"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "david@example.com",
                            FullName = "David Lee",
                            PhoneNumber = "555-0104",
                            Status = "Active",
                            Username = "david"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "emma@example.com",
                            FullName = "Emma Davis",
                            PhoneNumber = "555-0105",
                            Status = "Suspended",
                            Username = "emma"
                        });
                });

            modelBuilder.Entity("WalletSystem.Models.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 1500.00m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Status = "Active",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Balance = 320.50m,
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Status = "Active",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Balance = 0.00m,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Status = "Frozen",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Balance = 9800.75m,
                            CreatedAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Status = "Active",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Balance = 50.00m,
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Status = "Frozen",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("WalletSystem.Models.Transaction", b =>
                {
                    b.HasOne("WalletSystem.Models.Wallet", "RelatedWallet")
                        .WithMany()
                        .HasForeignKey("RelatedWalletId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WalletSystem.Models.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RelatedWallet");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("WalletSystem.Models.Wallet", b =>
                {
                    b.HasOne("WalletSystem.Models.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("WalletSystem.Models.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WalletSystem.Models.User", b =>
                {
                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("WalletSystem.Models.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
