// <auto-generated />
using System;
using Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identity.Infrastructure.Migrations;

[DbContext(typeof(IdentityDbContext))]
[Migration("20240101000001_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Identity.Domain.Entities.ApplicationUser", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("CreatedBy").HasColumnType("text");
            b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<bool>("EmailConfirmed").HasColumnType("boolean");
            b.Property<int>("FailedLoginAttempts").HasColumnType("integer");
            b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<bool>("IsActive").HasColumnType("boolean");
            b.Property<bool>("IsDeleted").HasColumnType("boolean");
            b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<DateTime?>("LockoutEnd").HasColumnType("timestamp with time zone");
            b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
            b.Property<string>("PhoneNumber").HasMaxLength(25).HasColumnType("character varying(25)");
            b.Property<string>("RefreshToken").HasColumnType("text");
            b.Property<DateTime?>("RefreshTokenExpiry").HasColumnType("timestamp with time zone");
            b.Property<string>("Role").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("UpdatedBy").HasColumnType("text");
            b.Property<int>("Version").IsConcurrencyToken().HasColumnType("integer");
            b.HasKey("Id");
            b.HasIndex("Email").IsUnique();
            b.ToTable("Users");
        });
#pragma warning restore 612, 618
    }
}
